public class AdsInfoWrapper {
    public String category;
    public String subject;
    public String body;
    public String type;
    public String price;
    public String zipcode;
    public String regdate;
    public String mileage;
    public String carcolor;
    public String fuel;
    public String car_steering;
    public String exchange;
    public String owner;
    public String financial;
    public String financial_status;
    public String vehicle_brand;
    public String vehicle_model;
    public String vehicle_version;
    public String cubiccms;
    public String moto_features;
}