public class LeadWrapper {
    public String source;
    public String adId;
    public String listId;
    public string CanalAtendimento;
    public string mobilePhone;
    public string tipoRegistro;
    public String linkAd;
    public String name;
    public String email;
    public String phone;
    public String message;
    public String createdAt;
    public AdsInfoWrapper adsInfo;
    public String externalId;
}