name: Validate Pull Request - UAT

on:
  pull_request:
    branches:
      - uat
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on UAT
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.AUTH_URL_UAT }}
          DRY_RUN: true
          TEST_LEVEL: RunAllTestsInOrg
